/**
 * PharmDVerse ERP - Unified Enterprise Export Engine
 * Supports Excel (.xlsx XML / CSV), PDF (Printable HTML-PDF rendering), and Individual Case PDF Export.
 * Standardized with College Logo, Title, Generated By, Date/Time, Academic Year, and ERP Version.
 */

export const ERP_VERSION = 'PharmDVerse ERP v2.1.0';

/**
 * Format timestamp for report headers
 */
export const getReportTimestamp = () => {
  const now = new Date();
  return now.toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
};

/**
 * Generate CSV file download
 */
export const exportToCSV = ({ title, collegeName, logoText, generatedBy, academicYear, columns, data, filename }) => {
  const headers = columns.map(c => `"${c.label}"`).join(',');
  const rows = data.map(row => 
    columns.map(c => {
      let val = row[c.key] !== undefined && row[c.key] !== null ? row[c.key] : '';
      if (typeof val === 'object') val = JSON.stringify(val);
      val = String(val).replace(/"/g, '""');
      return `"${val}"`;
    }).join(',')
  );

  const metadataHeader = [
    `"INSTITUTION: ${collegeName || 'PharmDVerse ERP Platform'}"`,
    `"REPORT TITLE: ${title}"`,
    `"GENERATED BY: ${generatedBy || 'Authorized User'}"`,
    `"GENERATED DATE: ${getReportTimestamp()}"`,
    `"ACADEMIC YEAR: ${academicYear || '2026-2027'}"`,
    `"PLATFORM: ${ERP_VERSION}"`,
    '""' // Blank line
  ].join('\n');

  const csvContent = '\uFEFF' + metadataHeader + '\n' + headers + '\n' + rows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename || 'PharmDVerse_Report'}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Generate Excel (.xlsx compatible SpreadsheetML XML) file download
 */
export const exportToExcel = ({ title, collegeName, logoText, generatedBy, academicYear, columns, data, filename }) => {
  const timestamp = getReportTimestamp();
  
  let xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#000000"/>
  </Style>
  <Style ss:ID="HeaderStyle">
   <Font ss:FontName="Calibri" ss:Size="12" ss:Bold="1" ss:Color="#FFFFFF"/>
   <Interior ss:Color="#1E3A8A" ss:Pattern="Solid"/>
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="TitleStyle">
   <Font ss:FontName="Calibri" ss:Size="16" ss:Bold="1" ss:Color="#1E3A8A"/>
  </Style>
  <Style ss:ID="MetaStyle">
   <Font ss:FontName="Calibri" ss:Size="10" ss:Italic="1" ss:Color="#475569"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Report">
  <Table>
   <Row><Cell ss:StyleID="TitleStyle"><Data ss:Type="String">${collegeName || 'PharmDVerse ERP Platform'}</Data></Cell></Row>
   <Row><Cell ss:StyleID="TitleStyle"><Data ss:Type="String">${title}</Data></Cell></Row>
   <Row><Cell ss:StyleID="MetaStyle"><Data ss:Type="String">Generated By: ${generatedBy || 'User'} | Date: ${timestamp} | Academic Year: ${academicYear || '2026-2027'} | ${ERP_VERSION}</Data></Cell></Row>
   <Row></Row>
   <Row>`;

  columns.forEach(col => {
    xml += `<Cell ss:StyleID="HeaderStyle"><Data ss:Type="String">${col.label}</Data></Cell>`;
  });
  xml += `</Row>`;

  data.forEach(row => {
    xml += `<Row>`;
    columns.forEach(col => {
      let val = row[col.key] !== undefined && row[col.key] !== null ? row[col.key] : '';
      if (typeof val === 'object') val = JSON.stringify(val);
      xml += `<Cell><Data ss:Type="String">${String(val).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</Data></Cell>`;
    });
    xml += `</Row>`;
  });

  xml += `</Table>
 </Worksheet>
</Workbook>`;

  const blob = new Blob([xml], { type: 'application/vnd.ms-excel' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename || 'PharmDVerse_Report'}.xls`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Generate Printable PDF Report via HTML print engine
 */
export const exportToPDF = ({ title, collegeName, logoText, generatedBy, academicYear, columns, data, filename }) => {
  const timestamp = getReportTimestamp();
  
  const printWindow = window.open('', '_blank', 'width=1000,height=800');
  if (!printWindow) {
    alert('Please allow popups to generate and view the PDF report.');
    return;
  }

  const columnsHtml = columns.map(c => `<th>${c.label}</th>`).join('');
  const rowsHtml = data.map((row, idx) => `
    <tr class="${idx % 2 === 0 ? 'even' : 'odd'}">
      ${columns.map(c => `<td>${row[c.key] !== undefined && row[c.key] !== null ? row[c.key] : '-'}</td>`).join('')}
    </tr>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - ${collegeName || 'PharmDVerse'}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 24px; color: #1e293b; background: #fff; }
        .report-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #1e3a8a; padding-bottom: 16px; margin-bottom: 20px; }
        .logo-box { width: 50px; height: 50px; background: #1e3a8a; color: #fff; font-weight: 800; font-size: 1.2rem; border-radius: 8px; display: flex; align-items: center; justify-content: center; margin-right: 16px; }
        .college-info { display: flex; align-items: center; }
        .college-name { font-size: 1.4rem; font-weight: 700; color: #1e3a8a; margin: 0; }
        .report-title { font-size: 1.1rem; font-weight: 600; color: #475569; margin: 4px 0 0 0; }
        .meta-box { text-align: right; font-size: 0.8rem; color: #64748b; line-height: 1.4; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 0.85rem; }
        th { background-color: #1e3a8a; color: #ffffff; text-align: left; padding: 10px 12px; font-weight: 600; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.5px; }
        td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
        tr.even { background-color: #f8fafc; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 12px; display: flex; justify-content: space-between; font-size: 0.75rem; color: #94a3b8; }
        @media print {
          body { padding: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="margin-bottom: 16px; text-align: right;">
        <button onclick="window.print()" style="background: #1e3a8a; color: #fff; padding: 8px 16px; border: none; border-radius: 6px; font-weight: 600; cursor: pointer;">
          Print / Save as PDF
        </button>
      </div>

      <div class="report-header">
        <div class="college-info">
          <div class="logo-box">${logoText || 'PDV'}</div>
          <div>
            <h1 class="college-name">${collegeName || 'PharmDVerse ERP Platform'}</h1>
            <h2 class="report-title">${title}</h2>
          </div>
        </div>
        <div class="meta-box">
          <div><strong>Generated By:</strong> ${generatedBy || 'Authorized User'}</div>
          <div><strong>Date & Time:</strong> ${timestamp}</div>
          <div><strong>Academic Year:</strong> ${academicYear || '2026-2027'}</div>
        </div>
      </div>

      <table>
        <thead>
          <tr>${columnsHtml}</tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>

      <div class="footer">
        <div>${ERP_VERSION} • Official Institutional Report</div>
        <div>Page 1 of 1</div>
      </div>

      <script>
        window.onload = function() {
          // Auto trigger print after render
          setTimeout(() => { window.print(); }, 500);
        }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};

/**
 * Generate Individual Clinical Case PDF Report (Preceptor & Student Export)
 */
export const exportClinicalCasePDF = (caseItem, college, currentUser) => {
  if (!caseItem) return;
  const timestamp = getReportTimestamp();

  const printWindow = window.open('', '_blank', 'width=1000,height=900');
  if (!printWindow) {
    alert('Please allow popups to generate the Clinical Case PDF.');
    return;
  }

  const pData = caseItem.forms?.patientProfile?.data || {};

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Clinical Case Report - ${caseItem.id}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 24px; color: #1e293b; line-height: 1.5; }
        .header { display: flex; justify-content: space-between; border-bottom: 3px solid #1e3a8a; padding-bottom: 16px; margin-bottom: 20px; }
        .logo { width: 50px; height: 50px; background: #1e3a8a; color: #fff; font-weight: 800; font-size: 1.2rem; border-radius: 8px; display: flex; align-items: center; justify-content: center; }
        .title-box { margin-left: 16px; }
        .title-box h1 { font-size: 1.3rem; margin: 0; color: #1e3a8a; }
        .title-box h2 { font-size: 1rem; margin: 4px 0 0 0; color: #475569; }
        .meta { text-align: right; font-size: 0.8rem; color: #64748b; }
        .section-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 20px; }
        .section-title { font-size: 1rem; font-weight: 700; color: #1e3a8a; margin-top: 0; border-bottom: 2px solid #cbd5e1; padding-bottom: 6px; }
        .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; font-size: 0.9rem; }
        .label { font-weight: 600; color: #475569; font-size: 0.8rem; text-transform: uppercase; }
        .val { font-weight: 600; color: #0f172a; margin-top: 2px; }
        .footer { margin-top: 30px; border-top: 1px solid #cbd5e1; padding-top: 12px; display: flex; justify-content: space-between; font-size: 0.75rem; color: #94a3b8; }
        @media print {
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="text-align: right; margin-bottom: 16px;">
        <button onclick="window.print()" style="background: #1e3a8a; color: #fff; padding: 8px 16px; border: none; border-radius: 6px; font-weight: 600; cursor: pointer;">
          Print / Download PDF
        </button>
      </div>

      <div class="header">
        <div style="display: flex; align-items: center;">
          <div class="logo">${college?.logo || 'PDV'}</div>
          <div class="title-box">
            <h1>${college?.name || 'PharmDVerse College of Pharmacy'}</h1>
            <h2>Clinical Documentation & SOAP Review Report</h2>
          </div>
        </div>
        <div class="meta">
          <div><strong>Case ID:</strong> ${caseItem.id}</div>
          <div><strong>Status:</strong> ${caseItem.status}</div>
          <div><strong>Date Generated:</strong> ${timestamp}</div>
        </div>
      </div>

      <div class="section-box">
        <h3 class="section-title">1. Patient & Case Metadata</h3>
        <div class="grid-2">
          <div><div class="label">Student Name</div><div class="val">${caseItem.studentName || 'Student'} (${caseItem.rollNo || 'N/A'})</div></div>
          <div><div class="label">Patient Name</div><div class="val">${caseItem.patientName || pData.patientName || 'N/A'}</div></div>
          <div><div class="label">Age / Gender</div><div class="val">${caseItem.age || pData.age || '-'} Yrs / ${caseItem.gender || pData.gender || '-'}</div></div>
          <div><div class="label">Hospital / Ward</div><div class="val">${caseItem.hospital || pData.department || 'General Medicine'}</div></div>
          <div><div class="label">Final Diagnosis</div><div class="val">${caseItem.diagnosis || pData.finalDiagnosis || 'N/A'}</div></div>
          <div><div class="label">Date of Submission</div><div class="val">${caseItem.submittedDate ? new Date(caseItem.submittedDate).toLocaleDateString() : '-'}</div></div>
        </div>
      </div>

      <div class="section-box">
        <h3 class="section-title">2. Clinical Documentation Summary</h3>
        <p><strong>Chief Complaints:</strong> ${pData.chiefComplaints || 'Documented'}</p>
        <p><strong>Past Medical History:</strong> ${pData.pastMedicalHistory || 'Documented'}</p>
        <p><strong>Vital Signs:</strong> ${pData.vitalSigns || 'Documented'}</p>
        <p><strong>Drugs Prescribed:</strong> ${pData.drugsPrescribed || 'Documented'}</p>
      </div>

      <div class="section-box">
        <h3 class="section-title">3. Preceptor Feedback & SOAP Evaluation</h3>
        <p><strong>Preceptor Overall Remarks:</strong> "${caseItem.overallRemarks || 'Approved clinical case.'}"</p>
      </div>

      <div class="footer">
        <div>${ERP_VERSION} • Confidential Clinical Record</div>
        <div>Exported by ${currentUser?.name || 'User'} (${currentUser?.role?.toUpperCase() || 'USER'})</div>
      </div>

      <script>
        window.onload = function() {
          setTimeout(() => { window.print(); }, 500);
        }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};
